# Generated by Django 4.1 on 2023-08-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "nama",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("icon", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Kecamatan",
            fields=[
                (
                    "nama",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kota",
            fields=[
                (
                    "nama",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("is_locked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TempatWisata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("link_gmap", models.CharField(blank=True, max_length=50, null=True)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("deskripsi_singkat", models.TextField(blank=True, null=True)),
                ("deskripsi_lengkap", models.TextField(blank=True, null=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("kategori", models.ManyToManyField(to="catalog.kategori")),
                (
                    "kecamatan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.kecamatan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kecamatan",
            name="kota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.kota"
            ),
        ),
        migrations.CreateModel(
            name="FotoTambahanWisata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="images/")),
                (
                    "tempatWisata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.tempatwisata",
                    ),
                ),
            ],
        ),
    ]
