# Generated by Django 4.1 on 2023-08-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=20, unique=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Kecamatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TempatWisata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("deskripsi_singkat", models.TextField(blank=True, null=True)),
                ("deskripsi_lengkap", models.TextField(blank=True, null=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="images/")),
                (
                    "kecamatan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.kecamatan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kecamatan",
            name="kota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.kota"
            ),
        ),
    ]
