# Generated by Django 4.1 on 2023-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kecamatan",
            name="nama",
            field=models.CharField(max_length=55, primary_key=True, serialize=False),
        ),
    ]
