# Generated by Django 4.1 on 2023-08-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kota",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
