# Generated by Django 4.1 on 2023-08-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_kota_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategori",
            name="icon",
            field=models.CharField(default="", max_length=30),
        ),
    ]
