# Generated by Django 4.1 on 2023-08-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_kategori_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="kecamatan",
            name="nama",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="tempatwisata",
            name="kategori",
            field=models.ManyToManyField(to="catalog.kategori"),
        ),
        migrations.AddField(
            model_name="tempatwisata",
            name="link_gmap",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tempatwisata",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FotoTambahanWisata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="images/")),
                (
                    "tempatWisata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.tempatwisata",
                    ),
                ),
            ],
        ),
    ]
